name: golf
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  rxdart: ^0.22.2
  flutter_markdown: ^0.2.0
  flutter_simple_dependency_injection: ^1.0.1
  tuple: ^1.0.2
  dio: ^3.0.3
  logger: ^0.7.0+2
  dots_indicator: ^1.0.0
  image_picker: ^0.6.1+11
  file_picker: ^1.4.0
  image_cropper: ^1.1.0
  path_provider: ^1.3.0
  path: ^1.6.2
  flutter_section_table_view: ^1.0.5
  cached_network_image: ^1.1.3
  flutter_advanced_networkimage: any
  flutter_html: ^0.11.0
  google_sign_in: ^4.0.13
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  firebase_messaging: ^6.0.1
  flutter_facebook_login: ^3.0.0
  linkedin_login: ^0.2.0
  flutter_webview_plugin: ^0.3.8
  flutter_cache_manager: ^1.1.1
  uuid: 2.0.1
  intl: 0.15.8
  badges: ^1.1.0
  chewie: 0.9.8+1
  video_player: ^0.10.2+3
  webview_flutter: ^0.3.15+1
  flutter_calendar_carousel: ^1.4.4
  table_calendar: ^2.1.0
  url_launcher: ^5.2.5
  giphy_picker:
    git:
      url: https://github.com/budo385/giphy_picker.git
  share: ^0.6.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/4.0x/
    - assets/images/3.0x/
    - assets/images/2.0x/
    - assets/images/1.5x/
    - assets/images/others_images/
    - assets/images/others_images/4.0x/
    - assets/images/others_images/3.0x/
    - assets/images/others_images/2.0x/
    - assets/images/others_images/1.5x/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Suranna-Regular
      fonts:
        - asset: assets/fonts/Suranna-Regular.ttf

    - family: SFrancisco
      fonts:
        - asset: assets/fonts/SFUIText-Light.ttf
          weight: 300
        - asset: assets/fonts/SFUIText-Regular.ttf
        - asset: assets/fonts/SFUIText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFUIText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFUIText-Light.otf
          weight: 300
        - asset: assets/fonts/SFUIText-Medium.otf
          weight: 500
        - asset: assets/fonts/SFUIText-Regular.otf
        - asset: assets/fonts/SFUIText-Bold.otf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
